version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /var/www
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/var/www
    expose:
      - "8081"
    command: bash -c "npm install &&  npm run start"

  workspace:
    image: "node:8"
    user: "node"
    command: bash
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    expose:
      - "8080"
